// <auto-generated />
using System;
using Ex.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ex.DataContext.Migrations
{
    [DbContext(typeof(DesafioContext))]
    partial class DesafioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ex.DataModel.Model.AvaliacaoFamiliar", b =>
                {
                    b.Property<int>("AvaliacaoFamiliarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAlteracaoRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInclusaoRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("FamiliaId")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("int");

                    b.HasKey("AvaliacaoFamiliarId");

                    b.HasIndex("FamiliaId");

                    b.ToTable("AvaliacaoFamiliar");
                });

            modelBuilder.Entity("Ex.DataModel.Model.Dominio", b =>
                {
                    b.Property<int>("DominioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAlteracaoRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInclusaoRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("DominioCategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("DominioId");

                    b.HasIndex("DominioCategoriaId");

                    b.ToTable("Dominio");

                    b.HasData(
                        new
                        {
                            DominioId = 1,
                            Ativo = true,
                            DataInclusaoRegistro = new DateTime(2019, 11, 28, 1, 20, 20, 196, DateTimeKind.Local).AddTicks(290),
                            DominioCategoriaId = 1,
                            Nome = "Pretendente"
                        },
                        new
                        {
                            DominioId = 2,
                            Ativo = true,
                            DataInclusaoRegistro = new DateTime(2019, 11, 28, 1, 20, 20, 196, DateTimeKind.Local).AddTicks(373),
                            DominioCategoriaId = 1,
                            Nome = "Conjuge"
                        },
                        new
                        {
                            DominioId = 3,
                            Ativo = true,
                            DataInclusaoRegistro = new DateTime(2019, 11, 28, 1, 20, 20, 196, DateTimeKind.Local).AddTicks(379),
                            DominioCategoriaId = 1,
                            Nome = "Dependente"
                        },
                        new
                        {
                            DominioId = 4,
                            Ativo = true,
                            DataInclusaoRegistro = new DateTime(2019, 11, 28, 1, 20, 20, 196, DateTimeKind.Local).AddTicks(385),
                            DominioCategoriaId = 2,
                            Nome = "Cadastro Válido"
                        },
                        new
                        {
                            DominioId = 5,
                            Ativo = true,
                            DataInclusaoRegistro = new DateTime(2019, 11, 28, 1, 20, 20, 196, DateTimeKind.Local).AddTicks(390),
                            DominioCategoriaId = 2,
                            Nome = "Possui Uma Casa"
                        },
                        new
                        {
                            DominioId = 6,
                            Ativo = true,
                            DataInclusaoRegistro = new DateTime(2019, 11, 28, 1, 20, 20, 196, DateTimeKind.Local).AddTicks(395),
                            DominioCategoriaId = 2,
                            Nome = "Selecionada Em Outro Processo"
                        },
                        new
                        {
                            DominioId = 7,
                            Ativo = true,
                            DataInclusaoRegistro = new DateTime(2019, 11, 28, 1, 20, 20, 196, DateTimeKind.Local).AddTicks(400),
                            DominioCategoriaId = 2,
                            Nome = "Cadastro Incompleto"
                        });
                });

            modelBuilder.Entity("Ex.DataModel.Model.DominioCategoria", b =>
                {
                    b.Property<int>("DominioCategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAlteracaoRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInclusaoRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("DominioCategoriaId");

                    b.ToTable("DominioCategoria");

                    b.HasData(
                        new
                        {
                            DominioCategoriaId = 1,
                            Ativo = true,
                            DataInclusaoRegistro = new DateTime(2019, 11, 28, 1, 20, 20, 191, DateTimeKind.Local).AddTicks(2032),
                            Nome = "Tipo Pessoa"
                        },
                        new
                        {
                            DominioCategoriaId = 2,
                            Ativo = true,
                            DataInclusaoRegistro = new DateTime(2019, 11, 28, 1, 20, 20, 194, DateTimeKind.Local).AddTicks(1800),
                            Nome = "Status Familia"
                        });
                });

            modelBuilder.Entity("Ex.DataModel.Model.Familia", b =>
                {
                    b.Property<int>("FamiliaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAlteracaoRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInclusaoRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("DominioIdStatus")
                        .HasColumnType("int");

                    b.HasKey("FamiliaId");

                    b.HasIndex("DominioIdStatus");

                    b.ToTable("Familia");
                });

            modelBuilder.Entity("Ex.DataModel.Model.Pessoa", b =>
                {
                    b.Property<int>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAlteracaoRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeNascimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInclusaoRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("DominioIdTipo")
                        .HasColumnType("int");

                    b.Property<int>("FamiliaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PessoaId");

                    b.HasIndex("DominioIdTipo");

                    b.HasIndex("FamiliaId");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("Ex.DataModel.Model.Renda", b =>
                {
                    b.Property<int>("RendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAlteracaoRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInclusaoRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(14, 2)")
                        .HasMaxLength(150);

                    b.HasKey("RendaId");

                    b.HasIndex("PessoaId");

                    b.ToTable("Renda");
                });

            modelBuilder.Entity("Ex.DataModel.Model.AvaliacaoFamiliar", b =>
                {
                    b.HasOne("Ex.DataModel.Model.Familia", "Familia")
                        .WithMany("AvaliacoesFamiliar")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ex.DataModel.Model.Dominio", b =>
                {
                    b.HasOne("Ex.DataModel.Model.DominioCategoria", "DominioCategoria")
                        .WithMany("Dominios")
                        .HasForeignKey("DominioCategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ex.DataModel.Model.Familia", b =>
                {
                    b.HasOne("Ex.DataModel.Model.Dominio", "DominioStatus")
                        .WithMany("Familias")
                        .HasForeignKey("DominioIdStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ex.DataModel.Model.Pessoa", b =>
                {
                    b.HasOne("Ex.DataModel.Model.Dominio", "DominioTipo")
                        .WithMany("Pessoas")
                        .HasForeignKey("DominioIdTipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ex.DataModel.Model.Familia", "Familia")
                        .WithMany("Pessoas")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ex.DataModel.Model.Renda", b =>
                {
                    b.HasOne("Ex.DataModel.Model.Pessoa", "Pessoa")
                        .WithMany("Rendas")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
